### ISSUE TITLE
Release sn-pulsar

### ISSUE THREAD

**Issue by yaalsn** [streamnative-oss/sn-pulsar-rs#12] opened 2022-03-03 02:31 UTC
- Package name: It seems that crates.io has a package named [pulsar](https://crates.io/crates/pulsar) , and our package would names `sn-pulsar`, so we need to modify some files such as `Cargo.toml` and these which stuck `cargo test` . 
- How to use streamnative bot to register `https://crates.io/` with github login so that the publish token would be bot's while not mine?

Could you help me the two questions? @freeznet

**Comment by liangyuanpeng** [comment] 2022-03-10 15:10
So  streamnative will working for `sn-pulsar`?  How we plan streamnative's relationship with https://github.com/wyyerd/pulsar-rs

**Comment by mattisonchao** [comment] 2022-05-12 10:26
Hi @yaalsn  @freeznet 
Looks like this issue is already fixed. could you help confirm again?

**Comment by mattisonchao** [comment] 2022-05-12 10:29
Confirmed with @yaalsn, I'll close it now.

**Closed as completed by mattisonchao** 2022-05-12 10:29 UTC
